### PR TITLE
Added post type support for Jetpack portfolio

### LINKED ISSUE #50: Add Page Settings to Jetpack Projects
Add Page Settings to Jetpack Projects.

### PR DESCRIPTION
**Pull request by Misplon**
Resolves #50. This PR adds Page Settings to Jetpack single projects.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
Looks good. I ran a few basic tests and I don't see any issues with doing this.

**Comment by AlexGStapleton** [comment]
_Although_, it might be a good idea to detect Jetpack and/or if Jetpack Portfolio is enabled.

**Comment by Misplon** [comment]
Added, thanks.

**Review by AlexGStapleton — APPROVED** [review]
Awesome. 👍

**Pull request merged**
