### PR TITLE
Resolve websafe font selection error

### PR DESCRIPTION
**Pull request by AlexGStapleton**
This PR resolve an error after selecting a websafe font.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks. Can you let me know how to recreate this issue? I tried setting all fonts to Arial - normal in Unwind, no errors.

**Comment by AlexGStapleton** [comment]
I was using North when I came across this issue. To replicate this please activate North and then navigate to **Appearance > Customize**, **Theme Settings > Fonts** and change the **Main Font** setting to any of the Web Safe fonts - if one is already selected, you'll still need to change it.

**Comment by Misplon** [comment]
Using North develop and Settings develop with Arial - Normal as the main font, I don't see any JS errors.
To recreate this issue it seems you have to use a production version of the theme.

**Review by Misplon — APPROVED** [review]

**Comment by AlexGStapleton** [comment]
I can confirm I was using the release version when I came across this issue.

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
